#include "Iphone_XI\dialogs.cpp"
#include "Interpol\dialogs.cpp"
#include "EffetsEcran\dialogs.cpp"
#include "Contravention\dialogs.cpp"
#include "Plants\dialogs.cpp"
#include "Entreprise\dialogs.cpp"
